### ISSUE TITLE
Add submariner as fleet plugin

### ISSUE THREAD

**Issue by Flying-Tom** [kurator-dev/kurator#657]
**What would you like to be added**:
Expand the fleet manager's capabilities to install submariner as a Fleet plugin.

**Why is this needed**:
To enhance the user experience and the robustness of the installation process

**Comment by Flying-Tom** [comment]
- [x] Design for submariner fleet plugin #658 
- [x] Installing submariner as fleet plugin #660 
- [x] Improve the doc #668
